apiVersion: v1
kind: ReplicationController
metadata:
  name: vote
  namespace: instavote
spec:
  replicas: 4
  selector: 
    role: vote
    version: v1
  template: 
    metadata:
      name: vote
      labels:
        app: python
        version: v1
        role: vote
    spec:
      containers:
      - name: app
        image: initcron/oc-vote:v1
    
